Tweak collections.abc import to resolve mypy issue (#163)
Recently, type checking started breaking in builds with this error:

```
records_mover/utils/json_schema.py:26: error: unused 'type: ignore' comment
```

My best guess is that it is a difference between python 3.9.1 and python 3.9.2. In any case, it turns out that simply changing the import from `collections` to `collections.abc` resolved the issue that made the `type: ignore` comment relevant in the first place.