Add cli-extra-test (#58)
It turns out a dependency on numpy (which isn't installed in the default extras) had snuck in. Here's an example of things failing:

$ pyenv uninstall -f mvrec && pyenv virtualenv 3.8.2 mvrec && pyenv shell mvrec
[...]
$ pip install records-mover[cli]
[...]
$ mvrec
Traceback (most recent call last):
  File "/Users/broz/.pyenv/versions/mvrec/bin/mvrec", line 6, in <module>
    from records_mover.records.cli import main
  File "/Users/broz/.pyenv/versions/3.8.2/envs/mvrec/lib/python3.8/site-packages/records_mover/__init__.py", line 14, in <module>
    from . import records
  File "/Users/broz/.pyenv/versions/3.8.2/envs/mvrec/lib/python3.8/site-packages/records_mover/records/__init__.py", line 18, in <module>
    from .schema import RecordsSchema
  File "/Users/broz/.pyenv/versions/3.8.2/envs/mvrec/lib/python3.8/site-packages/records_mover/records/schema/__init__.py", line 2, in <module>
    from .schema import RecordsSchema  # noqa
  File "/Users/broz/.pyenv/versions/3.8.2/envs/mvrec/lib/python3.8/site-packages/records_mover/records/schema/schema/__init__.py", line 4, in <module>
    from ..field import RecordsSchemaField
  File "/Users/broz/.pyenv/versions/3.8.2/envs/mvrec/lib/python3.8/site-packages/records_mover/records/schema/field/__init__.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
(mvrec) broz@graybookpro:~$

This PR reproduces this problem using an integration test and fixes it.